### ISSUE TITLE
Aktueller Status

### ISSUE THREAD

**Issue by voglohnee** [Paratron/contao-mod-mobile-visibility#3]
Hallo!

Deine Erweiterung ist sensationell. Ich würde diese gerne für ein Contaoprojekt einsetzen, bin aber unsicher wie das Entwicklungsstadium ist. Kann man dies nun schon für ein kommerzielles Projekt einsetzen?

Bitte um kurzen Input - vielen Dank!

**Comment by Paratron** [comment]
Danke für die Blumen. :)
Wir setzen das Plugin jetzt seit ca. 2-3 Monaten auf einer Kundenwebseite ein und hatten bisher keine Probleme damit.
Im [Forum-Thread auf contao-community.de](https://community.contao.org/de/showthread.php?34319-Modulvorstellung-Mobile-Visibility&p=223559) haben auch schon einige das Plugin erfolgreich eingesetzt, Andere haben aber auch schon Probleme im Einsatz mit anderen Plugins gemeldet.

Ich denke das musst du einfach kurz ausprobieren, ob es gewisse Interferenzen gibt. Die Installation ist ja schnell gemacht.
