### ISSUE TITLE
Das Modul wird unter Contao 3.1 nicht gefunden

### ISSUE THREAD

**Issue by guidoswelt24** [Paratron/contao-mod-mobile-visibility#4]
Ich habe versucht das Modul auf Contao 3.1 zu installieren, aber es wird erst gar nicht gefunden. Die Datenbank wird im install.php nicht aktualisiert.
Unter Contao 3.0 kann ich es ohne Probleme installieren.
Eine Idee, woran das liegt?
Falls es keine Lösung hierfür gibt, muss ich wohl auf 3.0 downgraden.

Gruss Guido

**Comment by Paratron** [comment]
Gerade vorgestern ohne Probleme in Contao 3.1 eingespielt, das Problem kann ich nicht bestätigen.
